name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Frontend CI/CD
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build

    - name: Deploy Frontend to Vercel
      uses: amondnet/vercel-action@v20
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}
        working-directory: ./frontend
        vercel-args: '--prod'

    # Backend CI/CD
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install

    - name: Deploy Backend to Vercel
      uses: amondnet/vercel-action@v20
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_BACKEND }}
        working-directory: ./backend
        vercel-args: '--prod' 